# Generated by Django 5.1.1 on 2024-10-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
